openapi: 3.0.0
info:
  title: Login System API
  description: API for user registration and login
  version: 1.0.0

paths:
  /register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: john_doe
                password:
                  type: string
                  format: password
                  example: mysecurepassword
      responses:
        '201':
          description: User registered successfully
        '400':
          description: Bad request. Invalid input data.
  
  /login:
    post:
      summary: User login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: john_doe
                password:
                  type: string
                  format: password
                  example: mysecurepassword
      responses:
        '200':
          description: Login successful
        '401':
          description: Unauthorized. Invalid username or password.
