/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/register": {
    /** Register a new user */
    post: {
      requestBody: {
        content: {
          "application/json": {
            /** @example john_doe */
            username?: string;
            /**
             * Format: password
             * @example mysecurepassword
             */
            password?: string;
          };
        };
      };
      responses: {
        /** @description User registered successfully */
        201: {
          content: never;
        };
        /** @description Bad request. Invalid input data. */
        400: {
          content: never;
        };
      };
    };
  };
  "/login": {
    /** User login */
    post: {
      requestBody: {
        content: {
          "application/json": {
            /** @example john_doe */
            username?: string;
            /**
             * Format: password
             * @example mysecurepassword
             */
            password?: string;
          };
        };
      };
      responses: {
        /** @description Login successful */
        200: {
          content: never;
        };
        /** @description Unauthorized. Invalid username or password. */
        401: {
          content: never;
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export type components = Record<string, never>;

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
